---
- name: Check CPE_NAME in /etc/os-release
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Execute grep command
      ansible.builtin.shell: "grep CPE_NAME /etc/os-release"
      register: cpe_name_output
      ignore_errors: yes

    - name: Display CPE_NAME output
      debug:
        var: cpe_name_output.stdout_lines

    - name: Extract and display CPE_NAME value
      debug:
        msg: "CPE_NAME: {{ cpe_name_output.stdout_lines | map('regex_replace', '^CPE_NAME=', '') | first }}"
      when: cpe_name_output.rc == 0