---
- name: Manage firewalld service
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)

  tasks:
    - include_vars:
        file: variable.yml

    - name: Restart NetworkManager service
      systemd:
        name: "{{ restart_reload }}"
        state: restarted
      become: true

    - name: Reload NetworkManager service
      systemd:
        name: "{{ restart_reload }}"
        state: reloaded
      become: true
