---
- name: Set OS Kernel Parameters
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)

  tasks:
    - name: Create sysctl configuration file
      template:
        src: /dev/null
        dest: /etc/sysctl.d/97-oracle-database-sysctl.conf
        inline: |
          net.ipv4.tcp_syn_retries = 8
          net.ipv4.tcp_tw_reuse = 1
          net.ipv4.tcp_timestamps = 1
          vm.swappiness = 10
      notify: Apply sysctl changes

  handlers:
    - name: Apply sysctl changes
      command: sysctl --system
