---
- name: Manage firewalld service
  hosts: localhost
  become: true  # Run tasks with elevated privileges (sudo)

- include_vars:
          file: variable.yml

  tasks:
    - name: Stop firewalld service
      systemd:
        name: "{{ service_name }}"
        state: stopped
      become: true

    - name: Disable firewalld service
      systemd:
        name: "{{ service_name }}"
        enabled: no
      become: true
