---
- name: Check and Set Timezone
  hosts: localhost
  gather_facts: true

  tasks:
    - include_vars:
          file: variable.yml
    - name: Check if timezone is correct
      shell: "timedatectl list-timezones | grep -E '^{{ timezone }}$'"
      register: timezone_check
      ignore_errors: yes

    - name: Display timezone check result
      debug:
        var: timezone_check.rc
      when: timezone_check.rc == 0
      
    - name: Display error if timezone is incorrect
      debug:
        msg: "Invalid timezone: {{ timezone }}"
      when: timezone_check.rc != 0
